### ISSUE TITLE
No such file or directory: ectyper/Data/.lock

### ISSUE THREAD

**Issue by elina2410** [phac-nml/ecoli_serotyping#96]
Hello,
today I updated ECTyper to newest version 2.0.0 and got some errors. How solve it?
> (ectyper2) ekaminska@perun:~/ecoli_typing$ ectyper -i fasta/ --pathotype --verify -o ecoli_typing2 
2024-12-30` 11:36:54,449 ectyper:46 INFO  Database structure QC is OK at /home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/ectyper_alleles_db.json
2024-12-30 11:36:54,452 ectyper:104 INFO  Starting ectyper v2.0.0 running on O and H antigen allele database v1.0 (11-03-2020) and pathotype database v2024-10-03
2024-12-30 11:36:54,452 ectyper:110 INFO  Output_directory is /home/ek/ecoli_typing/ecoli_typing2
2024-12-30 11:36:54,452 ectyper:111 INFO  Command-line arguments Namespace(input=['fasta/'], longreads=False, maxdirdepth=0, cores=1, percentIdentityOtype=95, percentIdentityHtype=95, percentCoverageOtype=90, percentCoverageHtype=50, verify=True, output='ecoli_typing2', reference='/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/EnteroRef_GTDBSketch_20231003_V2.msh', sequence=False, debug=False, dbpath=None, pathotype=True, percentIdentityPathotype=90, percentCoveragePathotype=50)
2024-12-30 11:36:54,452 ectyper.speciesIdentification:58 INFO  MASH species id sketch is missing and needs to be downloaded ...
2024-12-30 11:36:54,452 ectyper.speciesIdentification:26 INFO  Placed lock file at /home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/.lock
2024-12-30 11:36:54,453 ectyper.subprocess_util:40 ERROR Error in subprocess. The following command failed: ['mash', 'info', '-t', '/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/EnteroRef_GTDBSketch_20231003_V2.msh']
2024-12-30 11:36:54,453 ectyper.subprocess_util:41 ERROR Subprocess failed with error: "mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
"
2024-12-30 11:36:54,453 ectyper.speciesIdentification:81 ERROR Something went wrong with the file download from https://zenodo.org/records/13969103/files/EnteroRef_GTDBSketch_20231003_V2.msh?download=1. Trying next mirror ...
2024-12-30 11:36:54,453 ectyper.speciesIdentification:82 ERROR All mirrors tried but none worked. Check you Internet connection or download manually (see README)...
Traceback (most recent call last):
  File "/home/ek/miniconda3/envs/ectyper2/bin/ectyper", line 10, in <module>
    sys.exit(run_program())
             ^^^^^^^^^^^^^
  File "/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/ectyper.py", line 114, in run_program
    if speciesIdentification.get_species_mash(args.reference) == False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/speciesIdentification.py", line 83, in get_species_mash
    os.remove(lockfilepath) # remove lock file
    ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/.lock'

E.

**Comment by kbessonov1984** [comment]
Hi, the issue you are having is with the database download. ECTyper was not able to download the species ID database from Zenodo. Check your connection. Otherwise you can download it manually and insert it into the right directory. I can provide more info on manual database install


ectyper.speciesIdentification:82 ERROR All mirrors tried but none worked. Check you Internet connection or download manually

**Comment by elina2410** [comment]
But when I list dir with databases it seems that all are already there
> (ectyper2) ek@perun:~$ ll /home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/
total 968820
drwxrwxr-x 4 ek ek      4096 Jan  7 09:07 ./
drwxrwxr-x 4 ek ek      4096 Dec 30 11:34 ../
-rw-rw-r-- 1 ek ek 988871296 Dec 30 13:50 EnteroRef_GTDBSketch_20231003_V2.msh
-rw-rw-r-- 2 ek ek         0 Dec 19 19:40 __init__.py
drwxrwxr-x 2 ek ek      4096 Dec 30 11:34 __pycache__/
drwxrwxr-x 2 ek ek      4096 Dec 30 13:51 ectyper_2024-12-30_13.51.25.037411/
-rw-rw-r-- 2 ek ek   2410872 Dec 19 19:40 ectyper_alleles_db.json
-rw-rw-r-- 2 ek ek    764208 Dec 19 19:40 ectyper_patho_stx_toxin_typing_database.json

**Comment by kbessonov1984** [comment]
Try again to run `ectyper_init` it will try to re-download the database. The function `get_species_mash()` checks is the mash database exists. As long as the `EnteroRef_GTDBSketch_20231003_V2.msh` is present, there will be no database download. I do not see that `EnteroRef_GTDBSketch_20231003_V2.msh.txt` file is generated hinting to probable issue with `mash` You can generate one by running `mash info -t mash_sketch_path` that is `mash info -t EnteroRef_GTDBSketch_20231003_V2.msh.txt` in `/home/ek/miniconda3/envs/ectyper2/lib/python3.12/site-packages/ectyper/Data/`

**Comment by kbessonov1984** [comment]
Lastly you can try out the web version of the tool [here](https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fnml%2Fectyper%2Fectyper%2F2.0.0%2Bgalaxy0&version=latest)

**Comment by kbessonov1984** [comment]
I assume that issue is resolved and will update documentation for manual initialization of the species identification MASH database in case there are issues with download or Internet connection.
